import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Appbar from '@/components/Appbar'
import Providers from '@/components/Providers'

const roboto = Roboto({ weight: ['400', '700'], subsets: ['cyrillic-ext'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Appbar />
          <main className='mx-auto w-full max-w-[600px]'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
